### ISSUE TITLE
[Bug]: Client crashes after pressing the Generate button

### ISSUE THREAD

**Issue by gradientc** [arenasys/qDiffusion#2]
### What happened
The current version of the client crashes as soon as I try to generate anything, whereas it was previously working on a version from a few days ago.

### Steps to Reproduce
1. Launch the start script
2. Enter a prompt in the UI
3. Click on the `Generate` button

### Actual Results
The client closes and a `crash.log` file is generated.

### Expected result
The generated image appears.

### Contents of `crash.log`
```
Traceback (most recent call last):
  File "/home/gradient/Documents/qDiffusion/source/tabs/basic/basic.py", line 738, in generate
    request = self.buildRequest()
  File "/home/gradient/Documents/qDiffusion/source/tabs/basic/basic.py", line 726, in buildRequest
    self._requests += [self._parameters.buildRequest(size, batch_images, batch_masks, batch_areas, controls)]
  File "/home/gradient/Documents/qDiffusion/source/parameters.py", line 643, in buildRequest
    del data[k]
KeyError: 'hr_tome_ratio'
```

**Comment by LucasHisabf** [comment]
same here

**Comment by arenasys** [comment]
c15d94c7038904bcefd6f46f131840ca76e33096 should fix it
