### ISSUE TITLE
bug: Subprompts don't work with upscale

### ISSUE THREAD

**Issue by Derfuu** [arenasys/qDiffusion#21]
Using subprompts raising an error on upscale. Without upscale - subprompts works normally.

Traceback with generation 540x540 and upscale factor 2.25 with subprompts:
```py
INFERENCE 2023-07-23 06:36:56.336172
Traceback (most recent call last):
  File "F:\NeuralNetworks\Apps\qDiffusion\source\local.py", line 77, in run
    self.wrapper.txt2img()
  File "F:\NeuralNetworks\Apps\qDiffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\wrapper.py", line 720, in txt2img
    latents = inference.img2img(latents, denoiser, sampler, noise, self.hr_steps, True, self.hr_strength, self.on_step)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\inference.py", line 34, in img2img
    latents = sampler.step(latents, schedule, i, noise)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\samplers_k.py", line 154, in step
    denoised = self.predict(x, sigmas[i])
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\samplers_k.py", line 57, in predict
    original = self.model.predict_original(latents, timestep, sigma)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\guidance.py", line 143, in predict_original
    composed_pred = self.compose_predictions(original_pred)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\guidance.py", line 83, in compose_predictions
    pos = pos * masks + (neg * (1 - masks))
RuntimeError: The size of tensor a (151) must match the size of tensor b (67) at non-singleton dimension 3
```

**Comment by arenasys** [comment]
should be fixed in https://github.com/arenasys/sd-inference-server/commit/6b29407b80abf608df2cef3d68c033beced37542
