### ISSUE TITLE
[AMD] Error when loading UNET.

### ISSUE THREAD

**Issue by OopityDoop** [arenasys/qDiffusion#23]
When I try to generate images, I keep getting this error message: 
![image](https://github.com/arenasys/qDiffusion/assets/65684468/ba14097c-0b2b-4ede-9cea-f1108da6964f)

trace:
Traceback (most recent call last):
  File "D:\Other\sd\ui\qDiffusion\source\local.py", line 77, in run
    self.wrapper.txt2img()
  File "D:\Other\sd\ui\qDiffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\wrapper.py", line 611, in txt2img
    self.load_models(*initial_networks)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\wrapper.py", line 263, in load_models
    self.unet = self.storage.get_unet(self.unet_name, self.device, unet_nets)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\storage.py", line 302, in get_unet
    unet = self.get_component(name, "UNET", device)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\storage.py", line 269, in get_component
    self.file_cache[file] = self.load_file(file, comp)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\storage.py", line 378, in load_file
    state_dict, metadata = convert.convert(file)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\convert.py", line 392, in convert
    return convert_checkpoint(model_path)
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\convert.py", line 278, in convert_checkpoint
    state_dict = utils.load_pickle(in_file, map_location="cpu")
  File "D:\Other\sd\ui\qDiffusion\source\sd-inference-server\utils.py", line 376, in load_pickle
    return torch.load(file, map_location=map_location, pickle_module=SafeUnpickler)
  File "D:\Other\sd\ui\qDiffusion\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Other\sd\ui\qDiffusion\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
_pickle.UnpicklingError: state is not a dictionary

**Comment by arenasys** [comment]
fixed for now

**Comment by arenasys** [comment]
readded the safe unpickler, so this error could be back
