### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by MW3ONO** [arenasys/qDiffusion#27]
**Describe the bug**
Error while Generating.
'UNET' object has no attribute 'determine_prediction_type' (module.py:1614)

**Traceback**
Traceback (most recent call last):
  File "/content/sd-inference-server/server.py", line 209, in run
    self.wrapper.txt2img()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/sd-inference-server/wrapper.py", line 705, in txt2img
    latents = inference.txt2img(denoiser, sampler, noise, self.steps, self.on_step)
  File "/content/sd-inference-server/inference.py", line 13, in txt2img
    latents = sampler.step(latents, schedule, i, noise)
  File "/content/sd-inference-server/samplers_k.py", line 298, in step
    denoised = self.predict(x, sigmas[i])
  File "/content/sd-inference-server/samplers_k.py", line 57, in predict
    original = self.model.predict_original(latents, timestep, sigma)
  File "/content/sd-inference-server/guidance.py", line 134, in predict_original
    self.unet.determine_prediction_type()
  File "/content/sd-inference-server/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 186, in __getattr__
    return super().__getattr__(name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNET' object has no attribute 'determine_prediction_type'

**Screenshots**

**System:**
 - Mode: [Remotel]
 - OS: [Windows]

**Comment by arenasys** [comment]
fixed by [d4ce51995daac43e2117c4f4308242dc947bffbd](https://github.com/arenasys/sd-inference-server/commit/d4ce51995daac43e2117c4f4308242dc947bffbd)
