### ISSUE TITLE
Tile Control Net Upscaler error

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#32]
**Describe the bug**
If set third party upscaler ()UniScale, LSDIR and other), get an error on Upscaling process

**Traceback**
Traceback (most recent call last):
  File "F:\qDiffusion-master\source\local.py", line 81, in run
    self.wrapper.img2img()
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\qDiffusion-master\source\sd-inference-server\wrapper.py", line 790, in img2img
    return self.tiled_img2img()
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\qDiffusion-master\source\sd-inference-server\wrapper.py", line 981, in tiled_img2img
    upscaled_images = upscalers.upscale(images, UPSCALERS_PIXEL[self.img2img_upscaler], width, height)
KeyError: 'SR\\4x-UniScale-Balanced [72000g].pth'

**System:**
 - Mode: [Local]
 - OS: [Windows]
 - GPU: [Nvidia]

**Comment by arenasys** [comment]
fixed in https://github.com/arenasys/sd-inference-server/commit/fc01b56e0c7330d1430c180bc052859c296c6968
