### ISSUE TITLE
Bug/Error: Memory allocation while models merge/inserting LoRAs

### ISSUE THREAD

**Issue by Derfuu** [arenasys/qDiffusion#39]
After several updates - merging models become impossiple due to very much memory usage. My 32 Gigs of RAM were eaten in first minute. After - it starts using SSD for 2-5 minutes and raised this error. Restart didn't help.

![image](https://github.com/arenasys/qDiffusion/assets/54149748/30f8574b-e522-4b25-9e47-c0fc479825a6)

Tried merge 2 models and insert 4 LoRAs in single merge batch.
Generation parameters were standart, nothing changed after lauch.

**Comment by Derfuu** [comment]
one of similar tracebacks from crash.log

```py
Traceback (most recent call last):
  File "F:\NeuralNetworks\Apps\qDiffusion\source\local.py", line 89, in run
    self.wrapper.manage()
  File "F:\NeuralNetworks\Apps\qDiffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\wrapper.py", line 1184, in manage
    self.build(self.file)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\wrapper.py", line 1338, in build
    self.load_models(*initial_networks)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\wrapper.py", line 307, in load_models
    self.merge_lora_sources = merge.merge_checkpoint(self, self.merge_checkpoint_recipe)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 290, in merge_checkpoint
    do_recursive_checkpoint_merge(self, op)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 201, in do_recursive_checkpoint_merge
    name = do_recursive_checkpoint_merge(self, operation[k])
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 201, in do_recursive_checkpoint_merge
    name = do_recursive_checkpoint_merge(self, operation[k])
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 201, in do_recursive_checkpoint_merge
    name = do_recursive_checkpoint_merge(self, operation[k])
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 219, in do_recursive_checkpoint_merge
    result = do_unet_insert_lora(self, input_comps, alpha)
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 92, in do_unet_insert_lora
    out_state_dict[k] = add(base_state_dict[k], lora_state_dict[lora_key], alpha[key_mapping[k]])
  File "F:\NeuralNetworks\Apps\qDiffusion\source\sd-inference-server\merge.py", line 22, in add
    return a + alpha*b
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 335544320000 bytes.
```

**Comment by arenasys** [comment]
potentially fixed by https://github.com/arenasys/sd-inference-server/commit/7e927f85b84c73ef25fffb3c55f5930aa098f63f
