### ISSUE TITLE
SR Upscaling CUDA OOM

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/qDiffusion#57]
**Describe the bug**
In img2img mode, with a large source file (2048x1536), even with Highres strength set to 1 (default) and a target resolution of 1024x768, CUDA Out of Memory occurs.

Previously, this problem did not exist, and in img2img mode it was possible to generate images with a target resolution of 2048x1536 with SR models. VRAM mode - minimal.

**Traceback**
<details>
<summary>Traceback</summary>

Traceback (most recent call last):
  File "F:\qDiffusion-master\source\local.py", line 86, in run
    self.wrapper.img2img()
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\qDiffusion-master\source\sd-inference-server\wrapper.py", line 1024, in img2img
    upscaled_images = self.upscale_images(images, self.img2img_upscaler, width, height)
  File "F:\qDiffusion-master\source\sd-inference-server\wrapper.py", line 518, in upscale_images
    images = upscalers.upscale_super_resolution(images, self.upscale_model, width, height)
  File "F:\qDiffusion-master\source\sd-inference-server\upscalers.py", line 50, in upscale_super_resolution
    out = model(img)
  File "F:\qDiffusion-master\source\sd-inference-server\upscalers.py", line 75, in __call__
    return self.model(image)
  File "F:\qDiffusion-master\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 296, in __call__
    output = self._call_fn(self.model, image)
  File "F:\qDiffusion-master\venv\lib\site-packages\spandrel\__helpers\model_descriptor.py", line 281, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\qDiffusion-master\venv\lib\site-packages\spandrel\architectures\ESRGAN\arch\RRDB.py", line 143, in forward
    return self.model(x)
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\modules\upsampling.py", line 156, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
  File "F:\qDiffusion-master\venv\lib\site-packages\torch\nn\functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.00 GiB (GPU 0; 8.00 GiB total capacity; 1.72 GiB already allocated; 5.18 GiB free; 1.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

</details>

**Screenshots**
<details>
<summary>Screens</summary>

![изображение](https://github.com/arenasys/qDiffusion/assets/16870344/4d224f1e-5f7b-4917-b525-b0cdbff9becd)

</details>

**System:**
 - Mode: Local
 - OS: Windows
 - GPU: NVIDIA

**Comment by arenasys** [comment]
I switched to a different Upscaling backend, will look into its VRAM usage.

**Comment by arenasys** [comment]
Added tiling in https://github.com/arenasys/sd-inference-server/commit/053dc5565169402d4832440c1b4ba7229fcf54a0
