### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by DOfekfe42** [arenasys/qDiffusion#61]
There is an error because of url_pattern

Exception in thread Thread-11 (tunnel_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-1-314f6e2c32ed>", line 69, in tunnel_thread
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 726, in _parse
    raise source.error("unknown extension ?P" + char,
re.error: unknown extension ?Ph at position 1

**Comment by arenasys** [comment]
did you copy the notebook from github? github screws up the code badly. need to follow the Colab link instead
