### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by KenDoStudios** [arenasys/qDiffusion#74]
GUI 2024-06-05 11:10:41.499643
Traceback (most recent call last):
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\source\main.py", line 381, in loaded
    self.done()
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\source\main.py", line 385, in done
    start(self.engine, self.app)
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\source\main.py", line 503, in start
    import gui
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\source\gui.py", line 24, in <module>
    import backend
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\source\backend.py", line 18, in <module>
    import torch
  File "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\venv\lib\site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "E:\DOWNLOADS\qDiffusion-master\qDiffusion-master\venv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

running on a NVidia card

**Comment by arenasys** [comment]
Maybe fixed in c4003882760f667b1c17baaa58b4e96c6c65fcc3. Delete the `qDiffusion-master` folder, redownload the zip and try install again. This seems be be an issue with pytorch 2.3.
