### ISSUE TITLE
(HELP) Is not owned by current user

### ISSUE THREAD

**Issue by Mlaofmd** [arenasys/qDiffusion#77]
**Describe the bug**
after reinstalling my windows, i getting error about not current user,

**Traceback**
GUI 2024-07-05 15:46:42.045715
Traceback (most recent call last):
  File "D:\qDiffusion-master\source\main.py", line 381, in loaded
    self.done()
  File "D:\qDiffusion-master\source\main.py", line 385, in done
    start(self.engine, self.app)
  File "D:\qDiffusion-master\source\main.py", line 523, in start
    loadTabs(backend, backend)
  File "D:\qDiffusion-master\source\main.py", line 105, in loadTabs
    raise e
  File "D:\qDiffusion-master\source\main.py", line 101, in loadTabs
    tab_instance = tab_class(parent=app)
  File "D:\qDiffusion-master\source\tabs\settings\settings.py", line 37, in __init__
    self.getGitInfo()
  File "D:\qDiffusion-master\source\tabs\settings\settings.py", line 142, in getGitInfo
    commit, label = git.git_last(".")
  File "D:\qDiffusion-master\source\git.py", line 35, in git_last
    raise e
  File "D:\qDiffusion-master\source\git.py", line 27, in git_last
    repo = pygit2.Repository(os.path.abspath(path))
  File "D:\qDiffusion-master\venv\lib\site-packages\pygit2\repository.py", line 1759, in __init__
    path_backend = init_file_backend(path, flags)
_pygit2.GitError: D:\qDiffusion-master: repository path 'D:/qDiffusion-master/' is not owned by current user

**Screenshots**
![image](https://github.com/arenasys/qDiffusion/assets/52864321/42f12158-631f-4d94-9acb-685059c309fb)

**System:**
 - Mode: Remote
 - OS: Windows
 - GPU: Intel

**Comment by arenasys** [comment]
duplicate
