### ISSUE TITLE
Getting error after reinstalling my windows

### ISSUE THREAD

**Issue by Mlaofmd** [arenasys/qDiffusion#78]
**Describe the bug**
After reinstalling a windows 10, i getting error about current user

**Traceback**
GUI 2024-07-05 15:46:42.045715
Traceback (most recent call last):
  File "D:\qDiffusion-master\source\main.py", line 381, in loaded
    self.done()
  File "D:\qDiffusion-master\source\main.py", line 385, in done
    start(self.engine, self.app)
  File "D:\qDiffusion-master\source\main.py", line 523, in start
    loadTabs(backend, backend)
  File "D:\qDiffusion-master\source\main.py", line 105, in loadTabs
    raise e
  File "D:\qDiffusion-master\source\main.py", line 101, in loadTabs
    tab_instance = tab_class(parent=app)
  File "D:\qDiffusion-master\source\tabs\settings\settings.py", line 37, in __init__
    self.getGitInfo()
  File "D:\qDiffusion-master\source\tabs\settings\settings.py", line 142, in getGitInfo
    commit, label = git.git_last(".")
  File "D:\qDiffusion-master\source\git.py", line 35, in git_last
    raise e
  File "D:\qDiffusion-master\source\git.py", line 27, in git_last
    repo = pygit2.Repository(os.path.abspath(path))
  File "D:\qDiffusion-master\venv\lib\site-packages\pygit2\repository.py", line 1759, in __init__
    path_backend = init_file_backend(path, flags)
_pygit2.GitError: D:\qDiffusion-master: repository path 'D:/qDiffusion-master/' is not owned by current user

**Screenshots**
![image](https://github.com/arenasys/qDiffusion/assets/52864321/3054d9ce-e2da-467e-883d-19e2da5129ac)

**System:**
 - Mode: Remote
 - OS: Windows
 - GPU: Intel

**Comment by arenasys** [comment]
`path 'D:/qDiffusion-master/' is not owned by current user`
seems you need to take ownership of the folder. look up how to do that for windows 10.
another option would be just deleting and reinstalling
